name: Create a new folder

on:
  push:
    branches:
      - master

jobs:
  create_folder:
    runs-on: [self-hosted, Windows, X64]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create a new folder
        run: New-Item -ItemType directory -Path ./1
        shell: powershell
