name: Create a new folder

on:
  push:
    branches:
      - master

jobs:
  create_folder_windows:
    runs-on: [self-hosted, Windows, X64]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create a new folder
        run: New-Item -ItemType directory -Path ./1
        shell: powershell

  create_folder_mac:
    runs-on: [self-hosted, macOS, X64]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create a new folder
        run: mkdir 1
        shell: bash
